[masterdata.kanji.param]

  [masterdata.kanji.param.yama]
    id = 0
    character = "山"
    attack  = 150
    defence = 200
    speed   =  10
    jump    =  10
    weight  =  50

  [masterdata.kanji.param.tera]
    id = 1
    character = "寺"
    attack  = 120
    defence = 250
    speed   = 100
    jump    =  50
    weight  =  32

  [masterdata.kanji.param.ou]
    id = 2
    character = "王"
    attack  = 120
    defence = 140
    speed   = 120
    jump    = 120
    weight  =  35

  [masterdata.kanji.param.ikiru]
    id = 3
    character = "生"
    attack  =  70
    defence = 220
    speed   = 100
    jump    = 100
    weight  =  37

  [masterdata.kanji.param.ta]
    id = 4
    character = "田"
    attack  = 150
    defence = 200
    speed   =  70
    jump    =  50
    weight  =  40

  [masterdata.kanji.param.oni]
    id = 5
    character = "鬼"
    attack  = 200
    defence = 170
    speed   =  50
    jump    =  70
    weight  =  40

  [masterdata.kanji.param.kiru]
    id = 6
    character = "斬"
    attack  = 250
    defence =  80
    speed   = 150
    jump    = 150
    weight  =  25

  [masterdata.kanji.param.tsutsumu]
    id = 7
    character = "包"
    attack  =  50
    defence = 400
    speed   = 100
    jump    = 100
    weight  =  38

  [masterdata.kanji.param.shiro]
    id = 8
    character = "白"
    attack  = 120
    defence = 300
    speed   = 150
    jump    = 150
    weight  =  33

  [masterdata.kanji.param.wakeru]
    id = 9
    character = "分"
    attack  = 180
    defence = 120
    speed   = 120
    jump    = 120
    weight  =  32

  [masterdata.kanji.param.katsu]
    id = 10
    character = "且"
    attack  = 200
    defence = 100
    speed   = 100
    jump    = 100
    weight  =  28

  [masterdata.kanji.param.takumi]
    id = 11
    character = "工"
    attack  = 170
    defence = 170
    speed   = 150
    jump    = 130
    weight  =  50
