[id] # schema/master/id.toml
  [id.kanji]
    name = "Kanji"
    begin = 0
    end   = 99999
  [id.radical]
    name = "Radical"
    begin = 100000
    end   = 199999
  [id.move]
    name = "Move"
    begin = 200000
    end   = 299999
  [id.stage]
    name = "Stage"
    begin = 300000
    end   = 399999
