[physics]

  [physics.chara]
    friction = 1.3
    air_resistance = 15

    [physics.chara.force]
      horizontal = 10.0
      jump = 100.0

  [physics.floor]
    friction = 1.3

  [physics.ceiling]
    friction = 0.0

  [physics.wall]
    friction = 0.0
