[stage]
  [stage.notebook]
    id = 1
    name = "notebook"
    [stage.notebook.initialposition]
      [stage.notebook.initialposition.1players]
        [stage.notebook.initialposition.1players.0]
          x = 0
          y = -5
      [stage.notebook.initialposition.2players]
        [stage.notebook.initialposition.2players.0]
          x = -15
          y = -5
        [stage.notebook.initialposition.2players.1]
          x = 15
          y = -5
      [stage.notebook.initialposition.3players]
        [stage.notebook.initialposition.3players.0]
          x = -15
          y = -5
        [stage.notebook.initialposition.3players.1]
          x = 0
          y = -5
        [stage.notebook.initialposition.3players.2]
          x = 15
          y = -5
      [stage.notebook.initialposition.4players]
        [stage.notebook.initialposition.4players.0]
          x = -15
          y = -5
        [stage.notebook.initialposition.4players.1]
          x = -5
          y = -5
        [stage.notebook.initialposition.4players.2]
          x = 5
          y = -5
        [stage.notebook.initialposition.4players.3]
          x = 15
          y = -5

